name: map_assistant
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  cupertino_icons: 1.0.2
  camera: 0.10.5+2
  tflite: 1.1.2
  flutter_map: 4.0.0
  latlong2: 0.8.0
  url_launcher: 6.1.11
  sliding_up_panel: 2.0.0+1
  provider: 6.0.5
  flutter_map_marker_popup: 5.0.0
  flutter_tts: 3.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/